models/contact.py
from utils.db import db


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))

    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy
from config import DATABASE_CONNECTION_URI

app = Flask(__name__)

# settings
app.secret_key = 'mysecret'
print(DATABASE_CONNECTION_URI)
app.config["SQLALCHEMY_DATABASE_URI"] = DATABASE_CONNECTION_URI
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

# no cache
app.config['SEND_FILE_MAX_AGE_DEFAULT'] = 0

SQLAlchemy(app)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint("contacts", __name__)


@contacts.route('/')
def index():
    contacts = Contact.query.all()
    return render_template('index.html', contacts=contacts)


@contacts.route('/new', methods=['POST'])
def add_contact():
    if request.method == 'POST':

        # receive data from the form
        fullname = request.form['fullname']
        email = request.form['email']
        phone = request.form['phone']

        # create a new Contact object
        new_contact = Contact(fullname, email, phone)

        # save the object into the database
        db.session.add(new_contact)
        db.session.commit()

        flash('Contact added successfully!')

        return redirect(url_for('contacts.index'))

#Cuando le da al boton guardar pasa a ejecutar el metodo post
@contacts.route("/update/<string:id>", methods=["GET", "POST"])
def update(id):
    # Obtiene la data ingresada en la pagina con los datos que solicita
    print(id)
    contact = Contact.query.get(id)

    if request.method == "POST":
        contact.fullname = request.form['fullname']
        contact.email = request.form['email']
        contact.phone = request.form['phone']

        db.session.commit()

        flash('Contact updated successfully!')

        return redirect(url_for('contacts.index'))

    return render_template("update.html", contact=contact)


@contacts.route("/delete/<id>", methods=["GET"])
def delete(id):
    contact = Contact.query.get(id)
    #se borra el contacto
    db.session.delete(contact)
    #manda un commit a la base de datos con los datos actualizados
    db.session.commit()

    flash('Contact deleted successfully!')
    #redirige al contacto,index
    return redirect(url_for('contacts.index'))


@contacts.route("/about")
def about():
    return render_template("about.html")

templates/index.html
{% extends 'layout.html' %}

{% block title %}
  Flask SQLAlchemy CRUD | Home 
{% endblock %}

{% block body %}

    <!-- FORM -->
    <div class="row">

    <div class="col-md-5 p-5">
      <!-- MESSAGE -->
      {% include 'partials/_message.html' %}

      <!-- FORM -->
      {%  include 'partials/_taskForm.html' %}
    </div>

    <!-- contacts list -->
    <div class="col-md-7">
      {% for contact in contacts %}
        <div class="card mb-1 bg-black text-white">
          <div class="card-body py-2 px-3">
            <div class="d-flex justify-content-between">
              <h5 class="card-title h6">{{ contact.fullname}}</h5>
              <div>
                <a href="{{ url_for('contacts.update', id=contact.id) }}" class="btn btn-dark btn-sm rounded-0">Editar</a>
                <a href="{{ url_for('contacts.delete', id=contact.id) }}" class="btn btn-danger btn-sm rounded-0">Eliminar</a>
              </div>
            </div>
            <p class="card-text">{{ contact.email }}</p>
            <p class="card-text">{{ contact.phone }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
    </div>




{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <!-- <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/bootstrap.min.css')}}"
    /> -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}"
    />
  </head>
  <body>
    {% include 'partials/_navbar.html' %}

    <div class="container p-2">{% block body %} {% endblock %}</div>

    <!-- scripts -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/partials/_message.html
{% with messages = get_flashed_messages() %} {% if messages %} {% for message in
messages %}
<div class="alert alert-info alert-dismissible fade show" role="alert">
  {{message}}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% endfor %} {% endif %} {% endwith %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <a class="navbar-brand" href="/">Flask SQLAlchemy CRUD</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/about">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/partials/_taskForm.html
<form action="/new" method="POST" class="card bg-black text-light">
  <div class="card-body p-4">
    <h1 class="h5 mb-4">Agregar Contacto</h1>

    <div class="mb-3">
      <label for="fullname">Escriba sus nombres completos:</label>
      <input
        type="text"
        name="fullname"
        class="form-control rounded-0 bg-dark border-0 text-white"
        placeholder="Write fullname"
        autofocus
      />
    </div>

    <div class="mb-3">
      <label for="email">Escriba su correo:</label>
      <input
        type="text"
        name="email"
        class="form-control rounded-0 bg-dark border-0 text-white"
        placeholder="Write your email"
        required
      />
    </div>

    <div class="mb-3">
      <label for="phone">Escriba su telefono:</label>
      <input
        type="text"
        name="phone"
        class="form-control rounded-0 bg-dark border-0 text-white"
        placeholder="+12123123123"
      />
    </div>

    <button class="btn btn-primary">Guardar</button>
  </div>
</form>

templates/update.html
{% extends "layout.html" %} {% block body %}

<div class="col-md-4 offset-md-4">
  <div class="card card-body bg-dark text-white">
    <h1>Edit Task</h1>

    <form action="{{url_for('contacts.update', id=contact.id)}}" method="POST">
      <div class="mb-3">
        <label for="fullname">Escriba sus nombres completos:</label>
        <input
          type="text"
          name="fullname"
          value="{{contact.fullname}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>
      <div class="mb-3">
        <label for="email">Escriba su correo:</label>
        <input
          type="email"
          name="email"
          value="{{contact.email}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>
      <div class="mb-3">
        <label for="phone">Escriba su telefono:</label>
        <input
          type="tel"
          name="phone"
          value="{{contact.phone}}"
          class="form-control bg-dark text-white rounded-0"
        />
      </div>

      <button class="btn btn-primary">Actualizar</button>
    </form>
  </div>
</div>

{% endblock %}